# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a7258516c69b5e1a1f39ab349de627a5279f55aa07b25b9ac15a0a156edbb0c4b7214374e9f6e9da6bf16f1f4d10bfc1432a74e77a0c55ee747ff7bff5fc10e

test:
  secret_key_base: 794feb5821b8ec217ef571cb54a9b7e6c001c3f7e5c4c48b805661084066fe3fc85747d92e95723b8a6a8eff15ef27b8cb641cb0cabfa5ef1a168e76bdbb7d89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
